# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published_categories',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
