# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_published_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='published_categories',
        ),
    ]
