# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170714_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_prices',
            field=models.BooleanField(default=False),
        ),
    ]
