# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_more_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='url_store',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
