# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170714_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_video',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
