# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_url_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductsCategory',
        ),
    ]
