# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170718_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsCategory',
            new_name='Category',
        ),
    ]
