# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170718_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductsCategory',
        ),
    ]
