# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170718_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.FloatField(null=True),
        ),
    ]
